runtime:
  cache_dir: ./.cache/antora
site:
  title: OpenShift Starter Guides
  url: http://rampadc.github.io/antora-carbon-template/
  start_page: antora-carbon-template::index.adoc
content:
  sources:
    - url: git@github.com:rampadc/antora-carbon-template.git
      tags: []
      branches: HEAD
      start_path: documentation
asciidoc:
  attributes:
    experimental: true
ui:
  bundle:
    url: https://github.com/rampadc/antora-x-carbon/releases/download/main-ea5b12b/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
output:
  dir: ./gh-pages
antora:
  extensions:
    - "@antora/lunr-extension"
