runtime:
  cache_dir: ./.cache/antora

site:
  title: OpenShift Starter Guides(Dev Mode)
  url: http://localhost:3000/rhs-openshift-starter-guides/index.html
  start_page: rhs-openshift-starter-guides::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: documentation

asciidoc:
  attributes:
    title: OpenShift Starter Guides(Dev Mode)
    experimental: true
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/rampadc/antora-x-carbon/releases/download/main-ea5b12b/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
output:
  dir: ./gh-pages
antora:
  extensions:
    - "@antora/lunr-extension"
